Repository tigera/api, pull requests merged in 2021-11, with the labels that each got.

#76 Merge remote-tracking branch 'origin/release-v3.21'
  pkg/apis/projectcalico/v3/ippool.go
  pkg/apis/projectcalico/v3/policy_common.go
  pkg/openapi/openapi_generated.go
Labels: docs-pr-required, release-note-required

#78 Rename x, y, z fields because of OpenShift misinterpreting field call…
  pkg/apis/projectcalico/v3/uisettings.go
  pkg/openapi/openapi_generated.go
Labels: docs-pr-required, release-note-required

#79 Rename x, y, z fields because of OpenShift misinterpreting field call…
  pkg/apis/projectcalico/v3/uisettings.go
  pkg/openapi/openapi_generated.go
Labels: docs-pr-required, release-note-required

#83 Merge OS master to master
  pkg/apis/projectcalico/v3/ippool.go
  pkg/apis/projectcalico/v3/policy_common.go
  pkg/openapi/openapi_generated.go
Labels: docs-not-required, release-note-not-required

#80 Fix UISettings field names and validation tags
  pkg/apis/projectcalico/v3/uisettings.go
  pkg/openapi/openapi_generated.go
Labels: docs-pr-required, release-note-required

#84 Use correct validation tag
  pkg/apis/projectcalico/v3/uisettings.go
Labels: docs-pr-required, release-note-required

#85 Add ssh keys before semaphore checkout so repo clone doesn't fail
  .semaphore/cut-release.yml
  .semaphore/test-cut-release.yml
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#77 Add field in GlobalAlertSpec for variable substitution
  pkg/apis/projectcalico/v3/globalalert.go
  pkg/apis/projectcalico/v3/zz_generated.deepcopy.go
  pkg/openapi/openapi_generated.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#86 Update go-build image (latest golang patch) and k8s pins to squash CVEs
  Makefile
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch
