Repository tigera/api, pull requests merged in 2021-08, with the labels that each got.

#38 Automated cherry pick of #37: Fix semaphore org / id for this project
  Makefile
Labels: merge-when-ready, delete-branch

#40 Semi-Automated cherry pick of #39
  Makefile
Labels: docs-pr-required, release-note-required

#42 Automated cherry pick of #41: Update release branch regex
  .semaphore/semaphore.yml
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#41 Update release branch regex
  .semaphore/semaphore.yml
Labels: docs-pr-required, release-note-required

#39 Add release target related variables
  Makefile
Labels: docs-pr-required, release-note-required

#43 Remove registering resources as internal
  pkg/apis/projectcalico/v3/register.go
Labels: docs-pr-required, release-note-required

#44 tproxyUpstreamConnMark
  pkg/apis/projectcalico/v3/felixconfig.go
  pkg/apis/projectcalico/v3/zz_generated.deepcopy.go
  pkg/openapi/openapi_generated.go
Labels: docs-pr-required, release-note-required, merge-when-ready
