Repository tigera/api, pull requests merged in 2021-09, with the labels that each got.

#50 Merge projectcalico/api master branch
  pkg/apis/projectcalico/v3/felixconfig.go
  pkg/openapi/openapi_generated.go
Labels: docs-pr-required, release-note-required

#51 Merge projectcalico/api master branch
  Makefile
  build/update-client-gen.sh
  go.mod
  go.sum
  pkg/lib/numorstring/openapi_generated.go
  pkg/openapi/openapi_generated.go
Labels: docs-not-required, release-note-not-required

#52 Augment state for a PacketCapture with multiple options
  pkg/apis/projectcalico/v3/packetcapture.go
Labels: docs-pr-required, release-note-required

#53 Merge projectcalico master
  go.mod
  go.sum
  pkg/openapi/openapi_generated.go
Labels: docs-not-required, release-note-not-required

#49 [EV-1007] Add felix configuration collector debug trace flag.
  pkg/apis/projectcalico/v3/felixconfig.go
  pkg/apis/projectcalico/v3/zz_generated.deepcopy.go
  pkg/openapi/openapi_generated.go
Labels: docs-pr-required, release-note-required

#54 Add UISettingsGroup and UISettings resources.
  pkg/apis/projectcalico/v3/authorizationreview.go
  pkg/apis/projectcalico/v3/conversion.go
  pkg/apis/projectcalico/v3/register.go
  pkg/apis/projectcalico/v3/uisettings.go
  pkg/apis/projectcalico/v3/uisettingsgroup.go
  pkg/apis/projectcalico/v3/zz_generated.deepcopy.go
  pkg/client/clientset_generated/clientset/typed/projectcalico/v3/fake/fake_projectcalico_client.go
  pkg/client/clientset_generated/clientset/typed/projectcalico/v3/fake/fake_uisettings.go
  pkg/client/clientset_generated/clientset/typed/projectcalico/v3/fake/fake_uisettingsgroup.go
  pkg/client/clientset_generated/clientset/typed/projectcalico/v3/generated_expansion.go
  pkg/client/clientset_generated/clientset/typed/projectcalico/v3/projectcalico_client.go
  pkg/client/clientset_generated/clientset/typed/projectcalico/v3/uisettings.go
  pkg/client/clientset_generated/clientset/typed/projectcalico/v3/uisettingsgroup.go
  pkg/client/informers_generated/externalversions/generic.go
  pkg/client/informers_generated/externalversions/projectcalico/v3/interface.go
  pkg/client/informers_generated/externalversions/projectcalico/v3/uisettings.go
  pkg/client/informers_generated/externalversions/projectcalico/v3/uisettingsgroup.go
  pkg/client/listers_generated/projectcalico/v3/expansion_generated.go
  pkg/client/listers_generated/projectcalico/v3/uisettings.go
  pkg/client/listers_generated/projectcalico/v3/uisettingsgroup.go
  pkg/openapi/openapi_generated.go
Labels: docs-pr-required, release-note-required

#30 Add fields for egress g/w support.
  pkg/apis/projectcalico/v3/ippool.go
  pkg/apis/projectcalico/v3/zz_generated.deepcopy.go
  pkg/openapi/openapi_generated.go
Labels: docs-pr-required, release-note-required

#56 Add validation tags
  pkg/apis/projectcalico/v3/uisettings.go
  pkg/apis/projectcalico/v3/uisettingsgroup.go
  pkg/openapi/openapi_generated.go
Labels: docs-pr-required, release-note-required

#57 Fix UISettings plural and make non-namespaced
  build/update-client-gen.sh
  pkg/apis/projectcalico/v3/uisettings.go
  pkg/client/clientset_generated/clientset/typed/projectcalico/v3/fake/fake_projectcalico_client.go
  pkg/client/clientset_generated/clientset/typed/projectcalico/v3/fake/fake_uisettings.go
  pkg/client/clientset_generated/clientset/typed/projectcalico/v3/projectcalico_client.go
  pkg/client/clientset_generated/clientset/typed/projectcalico/v3/uisettings.go
  pkg/client/informers_generated/externalversions/generic.go
  pkg/client/informers_generated/externalversions/projectcalico/v3/interface.go
  pkg/client/informers_generated/externalversions/projectcalico/v3/uisettings.go
  pkg/client/listers_generated/projectcalico/v3/expansion_generated.go
  pkg/client/listers_generated/projectcalico/v3/uisettings.go
Labels: docs-pr-required, release-note-required

#58 Add release pipelines
  .semaphore/cut-release.yml
  .semaphore/test-cut-release.yml
Labels: docs-pr-required, release-note-required

#59 [release-calient-v3.10] Auto pick #58: Add release pipelines
  .semaphore/cut-release.yml
  .semaphore/test-cut-release.yml
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#60 Fix unshallow failing becuase it's already a complete repo
  .semaphore/cut-release.yml
  .semaphore/test-cut-release.yml
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#61 [release-calient-v3.10] Auto pick #60: Fix unshallow failing becuase it's already a complete repo
  .semaphore/cut-release.yml
  .semaphore/test-cut-release.yml
Labels: docs-pr-required, release-note-required

#62 Update dependency graph based on script calculations
  Makefile
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch
